#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# 
# Vagrant
#
export VAGRANT_DOTFILE_PATH=".vagrant-$(hostname | sed 's/\.local//')"
export ZEUSSOCK="/tmp/zeus.sock"
export ZEUS_START_PIDFILE="/tmp/zeus-start.pid"
export ZEUS_SERVER_PIDFILE="/tmp/zeus-server.pid"

#
# Editors
#

export EDITOR=`which vim`
export VISUAL=`which vim`
export PAGER='less'
#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
[[ -s "$HOME/.rvm/scripts/rvm"  ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function* 


# Powerline
if [ `uname` = 'Linux' ]
then
  export POWERLINE_PATH="/usr/share/powerline"
fi
if [ `uname` = 'Darwin' ]
then
  export POWERLINE_PATH="/Users/pragone/Library/Python/3.6/lib/python/site-packages/powerline"
fi
