#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# If the $TERM variable is exists, is set to "screen-256color", and the files
# .ruby-version and .ruby-gemset exist in the current directory, then run `rvm
# use`
# A little more background:
# - Running 'rvm use' looks for .ruby-gemset and .ruby-version in the current
# directory, and sets those appropriately
# - However, if we're in tmux, for some reason that doesn't run when splitting
# or opening a new console
#   - We can check if we're in tmux by looking at $TERM, and seeing if it equals
#   "screen-256color"
#   - However, if the variable isn't set at all, zsh complains.
if [[ !(-z ${TERM+x}) && $TERM = "screen-256color" && -a .ruby-version && -a .ruby-gemset ]]
then
  rvm use
fi

# autoload -U history-beginning-search-backward
# autoload -U history-beginning-search-forward
# bindkey $terminfo[kcuu1] history-beginning-search-backward
# bindkey $terminfo[kcud1] history-beginning-search-forward
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey $terminfo[kcuu1] history-beginning-search-backward-end
bindkey $terminfo[kcud1] history-beginning-search-forward-end

export LSCOLORS="Gxfxcxdxbxegedabagacad"
export LS_COLORS="di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"

autoload -Uz colors && colors
zstyle -e ':completion:*:default' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)*==36=36}:${(s.:.)LS_COLORS}")';

source ~/.aliases

fpath=(~/.dotfiles/completion $fpath)
autoload -U compinit
compinit

zstyle ':completion:*' menu select=2
