#.zlogout is sometimes used to clear and reset the terminal.
#
#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Print the message.
cat <<-EOF

Thank you. Come again!
  -- Dr. Apu Nahasapeemapetilon
EOF
