#Since .zshenv is always sourced, it often contains exported variables that
#should be available to other programs. For example, $PATH, $EDITOR, and $PAGER
#are often set in .zshenv. Also, you can set $ZDOTDIR in .zshenv to specify an
#alternative location for the rest of your zsh configuration.
#
#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# load in the share environment variables
if [[ -f ~/.env  ]]; then
  source ~/.env
fi
