# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

export BAT_CHARGE=/Users/pragone/.battery
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="pragone"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew bundler cake django gem git gitflow github heroku mercurial node npm osx pip python rails rail3 rake ruby rvm)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

[[ -s "/Users/pragone/.rvm/scripts/rvm" ]] && source "/Users/pragone/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
[[ -s "/Users/pragone/.autoenv/activate.sh" ]] && source "/Users/pragone/.autoenv/activate.sh"



### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
if [[ -e .rvmrc ]]; then
    source .rvmrc
fi

if [[ -e .rc ]]; then
    source .rc
fi
alias please='sudo $(fc -ln -1)'
alias tml="tmux list-sessions"
alias tma="tmux -2 attach -t $1"
alias tmk="tmux kill-session -t $1"
alias vim='mvim -v'
export EDITOR='vim'
